### ISSUE TITLE
Unhelpful newbie error on missing i2c module

### ISSUE THREAD

**Issue by rowlap** [pimoroni/sn3218#11]
The out-of-the-box default on Raspbian is i2c disabled. Although it can be enabled easily enough using `raspi-config`, actually working out the issue for the first time is unintuitive.

Steps to reproduce:
```
$ python -c 'import sn3218'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/sn3218.py", line 108, in <module>
    i2c = SMBus(i2c_bus_id())
IOError: [Errno 2] No such file or directory

$ python3 -c 'import sn3218'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sn3218.py", line 108, in <module>
    i2c = SMBus(i2c_bus_id())
FileNotFoundError: [Errno 2] No such file or directory
```

Even if the smbus C extension returned a better error mentioning `/dev/i2c-4` it still wouldn't be obvious what to do.

Please add a `try ... except` around the call to `SMBus(i2c_bus_id())` to suggest a hint to the end user. (Note the different exception types in py2/3; `IOError` catches both assuming py3.3+ aliases.)

**Comment by Gadgetoid** [comment]
Thank you- and wholly agreed. IOError or FileNotFoundError are possibly the most useless and unfriendly result you could get from this.

**Comment by rowlap** [comment]
I would propose a PR, but what's the right wording? Perhaps
```
i2c initialization failed - is i2c enabled on this system?
See https://github.com/pimoroni/sn3218/wiki/missing-i2c
```
(obviously with more info in the wiki page)

**Comment by rowlap** [comment]
Pull request #18 created to add a helpful warning.

**Comment by rowlap** [comment]
PR #18 merged - closing issue.
