### ISSUE TITLE
Discussion of default_gamma_table

### ISSUE THREAD

**Issue by rowlap** [pimoroni/sn3218#12]
I was finding on longer piglow.tween() calls that I can see each discrete change of brightness (from zero to full) at the dimmer levels.

Digging further, sn3218.default_gamma_table sets a highly skewed curve mapping requested to output value.

For comparison, I plotted the current curve against a gamma curve for various values.
![sn3218-default-gamma](https://user-images.githubusercontent.com/16710761/68528189-6a291680-02e7-11ea-8245-37b16588b309.png)

Personal preference is for gamma 1.4, which provides a good linear fade without visible steps and without spending too much time in the brighter range, which is indistinguishable.

I'm assuming a couple of things here: that my hardware responds like everyone else's, and that changes to default_gamma_table will be difficult because it affects all output from piglow calls.

Thoughts?

**Comment by rowlap** [comment]
To reproduce my tests, folks will need the alternative table which I generated with:
```default_gamma_table = [int(255 * (i / 255) ** GAMMA) for i in range(256)]```

**Comment by Gadgetoid** [comment]
I can certainly replicate this on my own Piglow and see if I get a similar response- although I wont be able to do this until at least next week now. I'm not averse to changing the default if it's genuinely better.

It probably wouldn't hurt for `channel_gamma` to accept a gamma value and calculate the table for the user, either.

**Comment by rowlap** [comment]
I committed a work-in-progress version of the library to a fork branch:
https://github.com/rowlap/sn3218/tree/calibrate-gamma/library
It can be used with `python3 sn3218.py --calibrate` to set up an infinite loop linear fade with cursor keys for delay/gamma dynamic adjustment. (Nobody should use that version for anything else - it's not tested or polished.)

**Comment by rowlap** [comment]
As graphics output is a new topic for me, I can't quite make sense of the current default_gamma_table:
```default_gamma_table = [int(pow(255, float(i - 1) / 255)) for i in range(256)]```
Changing the exponent through the loop doesn't match other literature on decoding gamma. Can someone explain?

**Comment by rowlap** [comment]
>  I'm not averse to changing the default if it's genuinely better.

Good to hear; the current table could still be present in the library for those who need to invoke it for compatibility. Another way of looking at the table is pasted below; see how far through the list we need to get even to output brightness "10", and the number of repeated steps on a linear fade.

> It probably wouldn't hurt for `channel_gamma` to accept a gamma value and calculate the table for the user, either.

Agreed, but I don't love the API for setting a single channel at a time. Users would need to call the function 18 times, once for each LED (I think).

```
>>> sn3218.channel_gamma_table[0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 26, 26, 27, 27, 28, 29, 29, 30, 30, 31, 32, 33, 33, 34, 35, 36, 36, 37, 38, 39, 40, 41, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 58, 59, 60, 62, 63, 64, 66, 67, 69, 70, 72, 73, 75, 77, 78, 80, 82, 84, 86, 87, 89, 91, 93, 95, 98, 100, 102, 104, 106, 109, 111, 114, 116, 119, 121, 124, 127, 130, 132, 135, 138, 141, 144, 148, 151, 154, 158, 161, 165, 168, 172, 176, 180, 184, 188, 192, 196, 200, 205, 209, 214, 219, 223, 228, 233, 238, 244, 249]
```

**Comment by Gadgetoid** [comment]
Unfortunately I can't explain the default gamma table. It's actually so old - in company history terms - that I didn't even write it. It'll also be shadowed by 5 years of other concerns, so I suspect nobody will have much idea now. Good example of a place where more detailed comments would have been useful. Hindsight is 20/20!

I don't see any reason why we couldn't overhaul all the gamma functionality to:
1. Allow users to set a specific gamma table or,
2. Allow users to specify a gamma value and have the table converted and,
3. Allow them to set *all* channels at once or,
4 Just set one channel (for applications that use drastically different LED parts for some reason)

The calibrate example is a good idea- I'll give it a go when I'm back in the office!

**Comment by rowlap** [comment]
Another aspect, somewhat orthogonal, is the really bright whites. If we're considering changes, it may be worth trying to balance the brightness across colours as it fits nicely with the gamma table lookups.

For example: David Hunt's examples use a `correction` table to rebalance:
http://www.davesmotleyprojects.com/raspi/raspi-piglow-module/piglow-tutorial.py

I'll file a separate issue #13, as these changes can be taken independently.
